sudo: true

dist: xenial

# Use node_js environnement
language: go

go:
  - 1.11.x

# Cache Gcloud SDK between commands
cache:
  directories:
    - "$HOME/google-cloud-sdk/"

# Install services
services:
  - docker

# Set env vars
env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
 
jobs:
  include:
    - stage: master
      if: branch = master AND NOT type = pull_request
      script: bash travis-scripts/master_main.sh

    - stage: pr
      if: type = pull_request
      script: bash travis-scripts/pr_main.sh        

      after_script:
        - cd ./core/
        - kubectl delete -f auth/config/gen
        - kubectl delete -f control/config/gen
        - kubectl delete -f eventbroker/config/gen
        - kubectl delete -f eventbroker-ext/config/gen
        - kubectl delete pods,svc,deployments --all -n keptn
        - kubectl delete channel --all -n keptn
        - kubectl delete clusterchannelprovisioner --all -n keptn
        - kubectl delete ns knative-build knative-eventing knative-monitoring knative-serving knative-sources
        - kubectl delete clusterrolebinding travis-cluster-admin-binding
        - kubectl delete svc knative-ingressgateway -n istio-system
        - kubectl delete deploy knative-ingressgateway -n istio-system
