apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: authenticator
  namespace: keptn
spec:
  runLatest:
    configuration:
      build:
        apiVersion: build.knative.dev/v1alpha1
        kind: Build
        metadata:
          name: authenticator-builder
          namespace: keptn
        spec:
          serviceAccountName: build-bot
          source:
            git:
              url: https://github.com/keptn/keptn.git
              revision: master
          template:
            name: kaniko
            arguments:
              - name: IMAGE
                value: docker-registry.cicd.svc.cluster.local:5000/keptn/keptn-authenticator:latest
              - name: DOCKERFILE
                value: /core/auth/Dockerfile
      revisionTemplate:
        metadata:
        spec:
          container:
            image: REGISTRY_URI_PLACEHOLDER:5000/keptn/keptn-authenticator:latest
            imagePullPolicy: Always
            env:
            - name: SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: keptn-api-token
                  key: keptn-api-token
